### ISSUE TITLE
feature: Using the YAML frontmatter instead of a span with properties

### ISSUE THREAD

**Issue by TinyAtoms** [Darakah/obsidian-timelines#33]
then you'd have something like
```
---
tags: event TTW
title: Some Event
date: 144-43-49-00
date-end: 144-43-49-00
class: orange
img: path/to/some/img
---
```
, and it's up to the user's theme if they want to hide it or not, or prettify it in a certain way.
I don't really have a reason for wanting this, besides an aversion to placing html in markdown.
Also, it then plays nicely together with things that work with yaml frontmatter, such as dataview.

**Comment by Paul-AUB** [comment]
Agreed, I find it usefull for chose information to be displayed in read mode :)

**Comment by BrotherGarfield** [comment]
Would be great if you can also support inline mode of dataview:
```
date:: 144-43-49-00
date-end:: 144-43-49-00
```

**Comment by ebullient** [comment]
The most likely tie here is reusing metadata from fantasy calendar, as that already has metadata parsing for dates in frontmatter, and can (with some limitations) read timeline dates.

As an option (keeping the spans or divs as you have them), you could consider something like this CSS snippet (I have this bound to a cssclass that I use the AutoClass plugin to enable): 

```css
.show-spans .ob-timelines {
  display: inline !important;
  font-style: italic;
}
.show-spans .ob-timelines::before {
  content: "🔖 " attr(data-date) ": " attr(data-title) ". ";
  color: var(--text-muted);
  font-weight: 500;
}
```
